### ISSUE TITLE
Calling NtQueryInformationProcess crashes

### ISSUE THREAD

**Issue by romanholidaypancakes** [n00bes/inline-syscall#1]
```
       wchar_t buffer[1024];
        int len2= 0;
        std::string buffer(bufferLength, 0);

       inliner.invoke<NTSTATUS>("NtQueryInformationProcess", processHandle, ProcessImageFileName, buffer, 1024, &len2);
```

**Comment by nbs32k** [comment]
```
    WCHAR strBuffer[ ( sizeof( UNICODE_STRING ) / sizeof( WCHAR ) ) + 260 ] = { 0 };
    int len2 = 0;
    UNICODE_STRING str = { 0 };

    str.Buffer = &strBuffer[ sizeof( UNICODE_STRING ) / sizeof( WCHAR ) ];
    str.Length = 0x0;
    str.MaximumLength = 260 * sizeof( WCHAR );


    inliner.invoke<NTSTATUS>( "NtQueryInformationProcess", ( HANDLE )-1, 27, &str, 1024, &len2 );
    printf( "%ls", str.Buffer );
```

should do the drill

**Comment by romanholidaypancakes** [comment]
> ```
>     WCHAR strBuffer[ ( sizeof( UNICODE_STRING ) / sizeof( WCHAR ) ) + 260 ] = { 0 };
>     int len2 = 0;
>     UNICODE_STRING str = { 0 };
> 
>     str.Buffer = &strBuffer[ sizeof( UNICODE_STRING ) / sizeof( WCHAR ) ];
>     str.Length = 0x0;
>     str.MaximumLength = 260 * sizeof( WCHAR );
> 
> 
>     inliner.invoke<NTSTATUS>( "NtQueryInformationProcess", ( HANDLE )-1, 27, &str, 1024, &len2 );
>     printf( "%ls", str.Buffer );
> ```
> 
> should do the drill

Tried your code still triggering exception:
```
Unhandled exception at 0x02A3000F in LemonSeakael32.exe: 0xC0000005: Access violation writing location 0x00000019.
```
Call `NtQueryInformationProcess` directly without exception. I refer to this way of writing, I don’t know who of you is right

https://github.com/winsiderss/systeminformer/blob/574288b92d6e529dbffafa0b3c8da8eacb90082c/phlib/native.c#L747

**Comment by romanholidaypancakes** [comment]
I just did some research, we don't need to manually set the Buffer pointer system will use the offset of `str+8` as the address of the Buffer, so `systeminformer` is correct, by the way, I am using a 32-bit process.

**Comment by nbs32k** [comment]
it's an issue with the x86 compatibility mode, my code i sent was designed for x64
